### PR TITLE
Fixed IE mappings

### PR DESCRIPTION
**Pull request by DrprofLuigi**

### CODE REVIEW

**Comment by DrprofLuigi** [comment]
Hold off on pulling this one in, there are some issues with the vanilla list. The first _only_ had 'flattened' data (it omits anything that just needs the `:0` removed), but I 'fixed' it with an incomplete list of items...

**Comment by DonBruce64** [comment]
If the item isn't flattened, then it doesn't need to be in the list.  Essentially, the system will auto-remove the 0 if it can't find a match.

**Comment by DrprofLuigi** [comment]
Alright. I updated the mappings to include all normally obtainable items (so it omits things like the 'wood' blocks (log with bark on all sides) and things like potions and eggs that use metadata.

I can remove items that have `:0` if you want.

**Comment by DonBruce64** [comment]
0 elimination would be ideal, as it'll cut down on file size and redundancy.

**Comment by DrprofLuigi** [comment]
Done, should be all good to go.

**Pull request merged**
