### PR TITLE
closedByDefault entry

### PR DESCRIPTION
**Pull request by RishiMenon2004**
When spawning a vehicle, the closedByDefault boolean sets the door as closed

### CODE REVIEW

**Comment by RishiMenon2004** [comment]
-_- conflicts in the handbook, how great

**Comment by DonBruce64** [comment]
You must've cloned on an older version, and then I updated the handbook after you cloned.

**Comment by RishiMenon2004** [comment]
well, at the moment I downloaded the latest one, and added my line

**Comment by RishiMenon2004** [comment]
**closedByDefault** – As the name suggests, setting this as true spawns the vehicle with this door closed.

**Comment by DonBruce64** [comment]
Closing as implemented on my end due to Git collisions.

**Pull request closed without merging**
