### PR TITLE
[PR] Made isTwoHanded, fireDelay and spreadFactor variable-modifiable as per #1508

### PR DESCRIPTION
**Pull request by boot2big**

### CODE REVIEW

**Review by DonBruce64 — CHANGES_REQUESTED** [review]
No comments on the code.  Just make sure to update the immortal tome that is the wiki to include a * by the variables that are now VMable.

**Comment by boot2big** [comment]
> Just make sure to update the immortal tome that is the wiki to include a * by the variables that are now VMable.
https://github.com/DonBruce64/MinecraftTransportSimulator/wiki/Pack-Making-JSON-Parts
I liked the part where he said "it's wiki'ing time" and he wiki'd all over this page!

> No comments on the code.
What exactly am I supposed to comment on? This was a pretty simple PR, the `definition.variableModifiers` section already has the standard "Adjust current variables to modifiers, if any exist." comment and the rest was pretty much plug-and-play from there... Am simply unsure on what else to leave comments for.

**Comment by LauraDarkez** [comment]
when it comes to testing this, i already have a json with the vms required set

**Comment by DonBruce64** [comment]
> > Just make sure to update the immortal tome that is the wiki to include a * by the variables that are now VMable.
> 
> https://github.com/DonBruce64/MinecraftTransportSimulator/wiki/Pack-Making-JSON-Parts I liked the part where he said "it's wiki'ing time" and he wiki'd all over this page!
> 
> > No comments on the code.
> 
> What exactly am I supposed to comment on? This was a pretty simple PR, the `definition.variableModifiers` section already has the standard "Adjust current variables to modifiers, if any exist." comment and the rest was pretty much plug-and-play from there... Am simply unsure on what else to leave comments for.

Oh, no no no.  I mean I myself don't have any comments and the code is fine, not that you need to put any in there.

**Review by DonBruce64 — APPROVED** [review]

**Pull request merged**
