### PR TITLE
[PR] Engine rev limiter variables + gradlew executable by default

### PR DESCRIPTION
**Pull request by boot2big**
Variables to report currentRevlimitRPM as well as the percentage of rpm compared to the revlimitRPM (which defaults to maxSafeRPM if revlimitRPM is -1)

### CODE REVIEW

**Comment by boot2big** [comment]
Oh yeah. Looks like my repo is a bit broken too. Oops.

Will be fixed next time I make a PR, I swear!

**Review by DonBruce64 — CHANGES_REQUESTED** [review]
You changed the gradlew file.  Please don't do that.  It makes things not work well.

**Comment by boot2big** [comment]
I only changed the permissions though, as by default it ain't executable. I can yeet that if just adding 1 to each permission will break stuff though.

**Comment by DonBruce64** [comment]
Add to the wiki.

**Comment by boot2big** [comment]
Is Wiki'd.

**Pull request merged**
