### PR TITLE
Mr.Mulles objectively superior custombench

### PR DESCRIPTION
**Pull request by SnailPerson**
Objectively superior custom bench.
I mean come on have you seen the old one?
wdwdawdad
Who ordered stapled meat cubes?

Have this instead!
awdawdd
aaddada
Much darker, solid, textured, sexy... those angles...
Thanks to chad succulent man for providing the wonderful model :D

### CODE REVIEW

**Comment by DonBruce64** [comment]
A question here: can you place that bench down with the other benches?  I would think you'd want a bit brighter red for that one since it's more like the Craftsman toolboxes.  In fact, most toolboxes are brighter, so I would think the red could use a bit of that?

**Comment by SnailPerson** [comment]
adawdad
current look

**Comment by SnailPerson** [comment]
addwwadadwdaw
compared to other benches

**Comment by SnailPerson** [comment]
QSqsSsqs

I could of course give it the palette of the fuel pump, but that one is too bright for my taste, the Bech seems to loose depth that way

**Comment by DonBruce64** [comment]
That's a fair point.  Send it as-is then.

**Comment by DonBruce64** [comment]
But, I see you changed the seatbench icon, was that because it got forget with the seatbench change before?

**Comment by SnailPerson** [comment]
yep, forgor to do that int he last pr.
Texture with brighter colors is already in, so all you gotta do is press that merge button ;3

**Pull request merged**
