### PR TITLE
Added OpenComputers support and 2 options to Traffic Signal Controller

### PR DESCRIPTION
**Pull request by Tim3Game**
Hello,
When I was playing Modded SSP and was using the Traffic lights, I wanted a way, to change them remotly with a Computer. So I decided to add OpenComputers support for the Traffic Signal Controller and the Fuel Pump. Maybe you ask, why even bother with it. Well, it's so people can for instance create automated traffic lights, so they turn off in the night (with the Disabled option), or with the Fuel Pumps, people can make automated Fuel Stations (and have graphs of usage or so). I added a Blicking green option, for people who want to recreate cities, where they have this kind of feature. It works easily, when the green light is about to turn yellow, it blinks few times and then turns yellow. Currently, it's only working for the timed option, because I have one problem in the triggered mode, where it wouldn't move on the next step, and after maybe a week of debunking it, I decided to disable it in hope, I or someone else can fix it later. 

**Main Changes:**
+ Added OpenComputers support for Traffic Signal Controller and Fuel Pump (With the help of Mimiru from OC Discord (Mimiru#6147))
+ Added **Blinking Green** option to Traffic Signal Controller (Before light changes from green to yellow, it will blink for few seconds) (Currently disabled in Vehicle Trigger mode)
+ Added **Disabled** option to Traffic Signal Controller (Traffic Lights will blink yellow, like when not connected)

### CODE REVIEW

**Comment by StarterCraft** [comment]
This is very, very important suggestion because it's time to invent automaticc systems to IV! 👏

**Comment by DonBruce64** [comment]
Will take a look at this after I get in the new crossing signal I've been working on, and re-vamp the traffic signal controller GUI.  Hopefully it'll be a simple merge that won't cause issues if I try to port to 1.15...

**Comment by Tim3Game** [comment]
The OpenComputers stuff are in `TileEntityTrafficSignalController` and `TileEntityFuelPump` and are just added lines, so that should not be a big problem to merge, and the Blinking green is mostly in `RenderPoleLighted`, so if your new crossing signal doesn't use that file, it should be good too, but the Disabled lights part is in the `GUITrafficSignalController` and the `boolean triggerMode` is replaced by a `int mode`, so it can have 3 states. That I whould need to redo after your GUI revamp, but hopefully it should not be a big problem

**Comment by DonBruce64** [comment]
Sadly, I ended up having to change most of the files.  That being said, with the new crossing signals I had the opportunity to move the state logic into the TileEntity so it only get calculated once a tick rather than once a render.  I'll go ahead and make another commit here after I get done with the config updates I'm working on that will define the light and crossing signal states in a function of the TE rather than an iterated if statement in the render.  That will allow OC to send the information to TE directly and the lights will take their states from that, rather than you needing to add hooks into the render code as well as the TE.

**Comment by Tim3Game** [comment]
I saw the changes and decided to take a try on redoing my way of working, and maybe implementing color variable to the lights, so people can write there own programs that can manage the lights individually, like I suggested on Discord, but without the GUI just with OC functions. So I will redo my fork, and then I will tell when you can check it out, if you ok with that.

**Comment by DonBruce64** [comment]
Custom colors?  Sounds fun!  The only issue you'll run into is the texture on the traffic signal block is part of the model, not something rendered custom, so even if you were to make a blue light on it, when the light was off it'd still render the same RYG color of the model.  Do what you do, I'll be here for support should you need it.  Configs and possibly instruments will take me a few weeks this update cycle.

**Comment by Tim3Game** [comment]
Sorry, not custom, just that you will be able with a computer to select what RYG color is active on every light individually. If it will work like I think and hope it will, it should be awesome.

**Comment by Tim3Game** [comment]
So, I finally redone the whole code and decided to remove the Blinking Green option and added Manual mode where people can control every Traffic Signal and Crossing Signal individually. There are basic functions for managing the signals, later I plan to add mass edit for signals (for instance set on 3 different traffic signals green... it saves space and lines) and other stuff...

**Comment by DonBruce64** [comment]
So finally ported a chunk of this code into a new branch.  For some reason though, I can't get the signal-controller to show up with the adapter block.  If you care to mess with it, it's on this branch:
https://github.com/DonBruce64/MinecraftTransportSimulator/tree/OC_SignalController
As nearly all of the code hooks in this PR got wiped during the block update, I'm going to close it, but if you get the other branch working you can PR that one and I'll throw it into the next release.

**Pull request closed without merging**
