### PR TITLE
[WIP] 1.20.1

### PR DESCRIPTION
**Pull request by ajh123**
Once finished, this PR will update Immersive Vehicles to 1.20.1! Most of the 1.20.1 code is based of the 1.16.5 version. Many things are not working yet.

Your contributions are welcome if you want to help.

### CODE REVIEW

**Comment by ajh123** [comment]
@dldev32 I understood which things worked and didn't work because my IDE highlighted them in red! The other parts of the mod (1.12.2, 1.16.5, the "core") are unaffected. Just copying the 1.16.5 code and updating the Minecraft version won't work because class names and packages change between versions.

Only a couple classes are working so far.

**Comment by dldev32** [comment]
Try to port at least to 1.18.2, it’s easier there.

**Comment by ajh123** [comment]
> Try to port at least to 1.18.2, it’s easier there.

@dldev32 1.18.2 may be easier but I'm playing in 1.20.1 and I can't downgrade my world with the other mods. Also there will be a lot of differences between 1.18.2 and 1.20.1 (but not as many).

**Comment by dldev32** [comment]
You make this contribution for everyone, not just for yourself. The developer will clearly not approve of such a strategy just because “I felt like it.”

**Comment by ajh123** [comment]
@dldev32 The main reason why most projects are made because they want to or other people want it. Many Minecraft players and new ones would be playing 1.20.x versions. Also, this will make it easier to update to 1.21 (or whatever Mojang decides to use instead). Forge developers do not support 1.18.2 anymore and won't give you help on their forums. Any Forge bugs in 1.18.2 won't be fixed.

**Comment by dldev32** [comment]
> @dldev32 The main reason why most projects are made because they want to or other people want it. Many Minecraft players and new ones would be playing 1.20.x versions. Also, this will make it easier to update to 1.21 (or whatever Mojang decides to use instead). Forge developers do not support 1.18.2 anymore and won't give you help on their forums. Any Forge bugs in 1.18.2 won't be fixed.

No, I’m not forcing you to port 1.18.2, it’s just not entirely advisable to step from 1.16.5 to 1.20.1. Not many mods have been updated to 1.20.1, so no one really plays there yet.

**Comment by SnailPerson** [comment]
Gotta agree on dl_devs point there...
Like 1.12 & 1.16.5, 1.18 is the next big step for most mods.
It would make sense for MTS to be available on that version also, just saying.
Perhaps you could join the discord server where discussion is easier: https://discord.gg/jpcJCPsr

**Comment by DonBruce64** [comment]
You two leave the fella alone.  If he wants to port to this version, he can and shouldn't be told he picked the "wrong" one.

**Comment by ajh123** [comment]
@dldev32 @DonBruce64 It doesn't make sense to update a mod to a not popular version. Look at this https://minecraft-statistic.net/en/global_statistic.html. According to them there are 1657 1.20.1 servers and there are 154 1.18.2 servers. Also [Fex's Vehicle and Transportation Mod](https://www.curseforge.com/minecraft/mc-mods/fexs-vehicle-mod) have skipped 1.18.2 however their 1.20.1 build are not functional yet.

**Comment by SnailPerson** [comment]
How's it going :D

**Comment by ajh123** [comment]
@SnailPerson Not much has changed since the [last commit](https://github.com/DonBruce64/MinecraftTransportSimulator/pull/1728/commits/e406824483f4188b25d8da7c9f749add47e7b8c8) yet. Some things are functional and others are nearly functional. Once everything look functional that's when I can test it.

**Comment by dldev32** [comment]
We'll wait for the results, we believe in you, buddy!

**Comment by dldev32** [comment]
Hello, how is it? Any progress?

**Comment by ajh123** [comment]
@dldev32 Not much, I've been busy with other things and working on Minecraft modding in a GitHub Codespace is slow. However, if you know Java / Minecraft modding you may contribute to this.

**Comment by andryqx** [comment]
there's any progress by now?

**Comment by ajh123** [comment]
@andryqx No, development has kind of stalled since GitHub Codespaces are slow and figuring out the changes between the Minecraft versions is very time consuming (there's a lot). And for some reason I cannot seem to get Gradle to work on anything but GitHub Codespaces.

However my branch is [open source](https://github.com/ajh123/MinecraftTransportSimulator/tree/master) so you may submit PRs to me and I will happily merge them.

**Comment by SnailPerson** [comment]
F

**Comment by JiaqiYi** [comment]
please be quick,man.many players in mcmod.cn wonder 1.20.1

**Pull request closed without merging**
