### PR TITLE
Removed cutoff of acceleration and made sure that the animation was not called when the pbrake is on

### PR DESCRIPTION
**Pull request by RishiMenon2004**
I realised that the cutoff for the acceleration was janky, so I removed it in the code and made it so that the clamps could work as the cutoff. I also added the variables to the handbook in the ground vehicles section. But my libre office is a little broken, so I don't know if it affected the formatting. It did give caution that it might effect.

### CODE REVIEW

**Comment by RishiMenon2004** [comment]
Oh, dang the formatting is broken

**Comment by RishiMenon2004** [comment]
I'll fix the formatting and push another commit

**Comment by RishiMenon2004** [comment]
oops

**Comment by DonBruce64** [comment]
So formatting is all good now?

**Comment by RishiMenon2004** [comment]
> So formatting is all good now?
yep, it's all good now
and I've fixed a certain flickering issue that appeared when the vehicles was slightly shifting when the pbrake isn't on

**Pull request merged**
